config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # root to: 'home#index'
  devise_scope :user do
    get 'login',      to: 'users/sessions#new'
    post 'login',     to: 'users/sessions#create'
    get 'logout',     to: 'users/sessions#logout'
    delete 'logout',  to: 'users/sessions#destroy'
    get 'signup',     to: 'users/registrations#signup'
    get 'signup/registration',  to: 'users/registrations#new'
    # get 'signup/number',         to: 'users/registrations#number'
    # get 'signup/address',        to: 'users/registrations#address'
    get 'signup/credit',         to: 'users/registrations#credit'
    get 'signup/done',           to: 'users/registrations#done'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"

  resources :users, only: [:index, :show, :new] do
    collection do
      get 'identification', to: 'users#identification'
      get '/:id', to: 'users#show'
    end
    member do
      get 'profile/edit', to: 'profiles#edit'
    end
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'sms_authentication' 
      post 'sms_authentication',to: 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation',to: 'signup#sms_check'
      get 'address' 
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :images, only:[:index, :create]
    collection do
      get 'search', to: 'items#search'
    end
  end
    
  resources :card, only: [:new, :show] do
    collection do
      get "paying"
      post 'show',   to: 'card#show'
      post 'pay',    to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index, :show] do
    collection do
      get  'show',  to: 'purchase#show'
      get  '/:id/index', to: 'purchase#index',as:"item_buy"
      post '/:id/pay',   to: 'purchase#pay',as:"item_pay"
      get  '/:id/done',  to: 'purchase#done',as:"buy_done"
    end
  end

  get 'guide/beginner', to: 'guide#beginner'

end

app/views/shared/_app-baner.html.haml
.app-baner
  .app-baner_inner
    .app-baner_inner-infomation
      %h2 スマホでかんたんフリマアプリ
      %p 今すぐ無料ダウンロード！
      .icon.clearfix
        %figure.icon-mercari
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/mercari_icon.png?3951034907"
        %ul.icon-list
          %li
            = link_to "https://itunes.apple.com/jp/app/id667861049?l=ja&amp;mt=8", target: "_blank" do
              = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3951034907"
          %li
            = link_to "https://play.google.com/store/apps/details?id=com.kouzoh.mercari&amp;hl=ja", target: "_blank" do
              = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3951034907"
    %figure.mobile-img
      = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/download_content_pc.png?3951034907"

app/views/shared/_content.html.haml
.content
  .content-list
    .tag.category
      %h2 人気のカテゴリー
      .tag-list
        %ul 
          %li
            = link_to "#ladyitems" do
              レディース
          %li
            = link_to "#manitems" do
              メンズ
          %li 
            = link_to "#cameraitems" do
              家電・スマホ・カメラ
          %li 
            = link_to "#hobbyitems" do
              おもちゃ・ホビー・グッズ
    .item
      .item-list#ladyitems
        - if @ladyitems.present?
          = render partial: 'shared/item-list', locals: {items: @ladyitems}
      .item-list#manitems
        - if @manitems.present?
          = render partial: 'shared/item-list', locals: {items: @manitems}
      .item-list#cameraitems
        - if @cameraitems.present?
          = render partial: 'shared/item-list', locals: {items: @cameraitems}
      .item-list#hobbyitems
        - if @hobyitems.present?
          = render partial: 'shared/item-list', locals: {items: @hobyitems}
    .tag.brand
      %h2 人気のブランド
      .tag-list
        %ul 
          %li
            = link_to "#" do
              シャネル
          %li
            = link_to "#" do
              ルイヴィトン
          %li 
            = link_to "#" do
              シュプリーム
          %li 
            = link_to "#" do
              ナイキ

app/views/shared/_footer.html.haml
%footer.footer
  .footer-nav
    .footer-nav__information
      %h2 メルカリについて
      %ul 
        %li
          = link_to "https://about.mercari.com/" do
            会社概要（運営会社）
        %li
          = link_to "/" do
            採用情報
        %li 
          = link_to "https://about.mercari.com/press/news/" do
            プレスリリース
        %li 
          = link_to "https://jp-news.mercari.com/", target: "_blank" do
            公式ブログ
        %li
          = link_to "/" do
            メルカリロゴ利用ガイドライン
        = link_to "https://twitter.com/mercari_jp", target: "_blank", class: 'icon' do
          = fa_icon 'twitter'
        = link_to "https://www.facebook.com/mercarijp", target: "_blank", class: 'icon' do
          = fa_icon "facebook-square"
    .footer-nav__information
      %h2 ヘルプ＆ガイド
      %ul
        %li
          = link_to guide_beginner_path do
            メルカリガイド
        %li
          = link_to "/" do
            らくらくメルカリ便
        %li
          = link_to "/" do
            ゆうゆうメルカリ便
        %li
          = link_to "/" do
            大型メルカリ便
        %li
          = link_to "/" do
            車体取引ガイド
        %li
          = link_to "/", target: "_blank" do
            メルカリあんしん・あんぜん宣言！
        %li
          = link_to "/" do
            偽ブランド品撲滅への取り組み
        %li
          = link_to "/" do
            メルカリボックス
    .footer-nav__privacy
      %h2 プライバシーと利用規約
      .left-li
        %ul
          %li
            = link_to "/" do
              プライバシーポリシー
          %li
            = link_to "/" do
              メルカリ利用規約
          %li
            = link_to "/" do
              あんしんスマホサポート制度に関する利用特約
          %li
            = link_to "/" do
              コンプライアンスポリシー
      .right-li
        %ul
          %li
            = link_to "/" do
              個人データの安全管理に係る基本方針
          %li
            = link_to "/" do
              特定商取引に関する表記
          %li
            = link_to "/" do
              資金決済法に基づく表示
          %li
            = link_to "/" do
              法令順守と犯罪抑止のために
    .footer-nav__information
      %h2 国
      %ul
        %li
          = link_to "/" do
            日本
        %li
          = link_to "/" do
            United States
  .footer-logo
    = link_to "/", class: 'footer-logo__mercari' do
      = image_tag "https://web-jp-assets.mercdn.net/_next/static/images/logo-white-1a0696cf557ee1ed6f3c3444661d21ad.svg", class: 'footer-logo__mercari-img', alt: "Mercari"
    %span.footer-logo__span © 2019 Mercari

app/views/shared/_header.html.haml
%header.header
  .header-inner
    .header-top
      %h1
        = link_to root_path, class: 'header-top__logo' do
          = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?891577966", class: 'header-top__logo-img', alt: "mercari"      
      = search_form_for @q, url:search_items_path do |f|
        .header-top__logo__search
          = f.search_field :name_cont, class: 'header-top__logo__search__box', id: 'search-query', placeholder: '何かお探しですか？'
          = button_tag type: 'submit', class: 'hidden' do
            %i.fa.fa-search
    .header-navbox
      .left-side
        %ul.side
          %li.li-left
            %h2
              = link_to "#" do
                = fa_icon 'list-ul'
                %span カテゴリーから探す
          %li.li-right
            %h2
              = link_to "#" do
                = fa_icon 'tag'
                %span ブランドから探す 
      .right-side
        %ul.side
          - if current_user
            -# 一時的に設置、マイページ上にログアウトボタンを作成した後で消す
            %li
              %h2
                = link_to logout_path do
                  %span ログアウト
            - unless current_page?(root_path)
              %li
                %h2
                  = link_to "#" do
                    = fa_icon 'heart'
                    %span いいね一覧
            %li
              %h2
                = link_to "#" do
                  = fa_icon 'bell'
                  %span お知らせ
            %li
              %h2
                = link_to "#" do
                  = fa_icon 'check'
                  %span やることリスト
            %li
              %h2
                = link_to user_path(current_user.id), class: 'user-link__signup' do
                  %div.mypage
                    = image_tag 'https://static.mercdn.net/images/member_photo_noimage_thumb.png'            
                  %span マイページ
          - else
            .user-link
              .signup
                = link_to signup_path, class: 'user-link__signup' do
                  新規会員登録
              .signin
                = link_to login_path, class: 'user-link__signin' do
                  ログイン      

app/views/shared/_item-list.html.haml
.item-list__name
  %h3 #{items[0].category.name}新着アイテム
  = link_to "もっと見る", "#"
.item-list__box
  .item-list__box-show
    - items.each do |item|
      .visibility
        = link_to item_path(item) do
          %figure
            %figcaption.name
              %span #{item.name}
            .price
              %span ¥#{item.price.to_s(:delimited)}
              = image_tag ("#{item.images[0].name}")

app/views/shared/_sell-btn.html.haml
.sell--btn
  = link_to new_item_path, class: 'sell--btn-link' do
    .sell--btn-link__show
      .name 
        出品
      = fa_icon 'camera'

app/views/shared/_single-footer.html.haml
.single-footer
  .single-footer__nav
    %nav
      %ul.clearfix
        %li 
          = link_to "プライバシーポリシー", "#"
        %li 
          = link_to "メルカリ利用規約", "#"
        %li 
          = link_to "特定商取引に関する表記", "#"
    .single-footer__image
      = link_to image_tag(src = "/images/logo-gray.svg", class: "hover-on-image", alt: "mercari", size: '80x65'), root_path
    %p 
      %small &copy 2019 Mercari

app/views/shared/_single-header.html.haml
.single-header
  %h1.single-header__logo
    = link_to image_tag(src = "/images/logo.svg", class: "single-header__image", alt: "mercari", size: '185x49'), root_path

app/views/shared/_slider.html.haml
.slider
  .button.button-prev.prev
    %i.fa.fa-chevron-circle-left
  .button.button-next.next
    %i.fa.fa-chevron-circle-right
  .slide.slide-1.active
    .slide-1__wrapper
      .slide-1__wrapper__left
        %h1 
          %span スマホでかんたん
          %br
          %span フリマアプリ
        %h2
          %span メルカリはスマホカメラからすぐに出品できる
          %br
          %span 購入時も安心な独自システムのアプリです。
        .app-link
          = image_tag "slider/app-store.svg", alt: "App Store"
          = image_tag "slider/google-play.svg", alt: "Google Play"
      .slide-1__wrapper__right
        = image_tag "slider/mercari-top1.png", alt: "メルカリ"
  .slide.slide-2
    .slide-2__wrapper
      = image_tag "slider/mercari-top2.png", alt: "メルカリなら新品も中古もお得！キャンプ用品 大特集！"