config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # root to: 'home#index'
  devise_scope :user do
    get 'login',      to: 'users/sessions#new'
    post 'login',     to: 'users/sessions#create'
    get 'logout',     to: 'users/sessions#logout'
    delete 'logout',  to: 'users/sessions#destroy'
    get 'signup',     to: 'users/registrations#signup'
    get 'signup/registration',  to: 'users/registrations#new'
    # get 'signup/number',         to: 'users/registrations#number'
    # get 'signup/address',        to: 'users/registrations#address'
    get 'signup/credit',         to: 'users/registrations#credit'
    get 'signup/done',           to: 'users/registrations#done'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"

  resources :users, only: [:index, :show, :new] do
    collection do
      get 'identification', to: 'users#identification'
      get '/:id', to: 'users#show'
    end
    member do
      get 'profile/edit', to: 'profiles#edit'
    end
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'sms_authentication' 
      post 'sms_authentication',to: 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation',to: 'signup#sms_check'
      get 'address' 
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :images, only:[:index, :create]
    collection do
      get 'search', to: 'items#search'
    end
  end
    
  resources :card, only: [:new, :show] do
    collection do
      get "paying"
      post 'show',   to: 'card#show'
      post 'pay',    to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index, :show] do
    collection do
      get  'show',  to: 'purchase#show'
      get  '/:id/index', to: 'purchase#index',as:"item_buy"
      post '/:id/pay',   to: 'purchase#pay',as:"item_pay"
      get  '/:id/done',  to: 'purchase#done',as:"buy_done"
    end
  end

  get 'guide/beginner', to: 'guide#beginner'

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category, optional: true
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images
  belongs_to :card, optional: true
  
  validates :name, length: { maximum: 40 }

  enum condition:{
    "新品、未使用": 1,
    "未使用に近い": 2,
    "目立った傷や汚れなし": 3,
    "やや傷や汚れあり": 4,
    "傷や汚れあり": 5,
    "全体的に状態が悪い": 6
  }

  enum shipping_fee:{
    "送料込み(出品者負担)": 1,
    "着払い(購入者負担)": 2
  }

  enum shipping_method:{
    "未定": 1,
    "クロネコヤマト": 2,
    "ゆうパック": 3,
    "ゆうメール": 4
  }

  enum days_before_shipping:{
    "1~2日で発送": 1,
    "2~3日で発送": 2,
    "4~7日で発送": 3
  }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_image
  before_action :set_search
  before_action :set_item, only: [:edit, :update, :destroy]

  def index
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true)
    @ladyitems = get_items(1)
    @manitems = get_items(199)
    @cameraitems = get_items(892)
    @hobyitems = get_items(679)
  end

  def new
    redirect_to login_url unless user_signed_in?
    @item = Item.new
    10.times { @item.images.build }

    @category0 = Category.eager_load(children: {children: :children}).where(parent_id: 0)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path and return
    else
      render :new
    end
  end

  def show
    @item = Item.find(params[:id])
    @whole_items =Item.where(user_id: @item.user_id).where.not(id: @item.id).order('id DESC').limit(9)
  end

  def search
    @q = Item.ransack(search_params)
    @items = @q.result(distinct: true)
  end

  def edit
    redirect_to login_url unless user_signed_in?
    10.times { @item.images.build }

    @category0 = Category.eager_load(children: {children: :children}).where(parent_id: 0)
  end

  def update
    if @item.update!(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to :back
    end
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :price, :description, :category_id, :condition, 
    :shipping_fee, :shipping_from, :days_before_shipping, :shipping_method, 
    :trade_status, images_attributes: [:name, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_image
    @images = Image.where(params[:item_id])
  end

  def get_items(id)
    category = Category.find(id)
    items = Item.where(category_id: category).order('id DESC').limit(10)
  end

  def search_params
    params.require(:q).permit(:name_cont)
  end

  def set_search
    @q = Item.ransack(params[:q])
  end
end

app/views/items/_buy-btn.html.haml
- if @item.user_id == current_user.id
  %p.edit-btn-p
  .items-edit-btn
    = link_to edit_item_path(@item.id), class: "edit-btn" do
      = "商品を編集する"
- else
  .buy-btn
    =link_to item_buy_purchase_index_path(@item.id) do
      ="購入画面に進む"

app/views/items/_destroy-btn.html.haml
- if @item.user_id == current_user.id
  %p.destroy-btn-p or
  .items-destroy-btn
    = link_to item_path(@item.id), method: :delete, class: "destroy-btn" do
      = "商品を削除する"

app/views/items/_item-detail.html.haml
.item-detail
  .item-detail-box
    .item-name
      %h1
        = @item.name 
      %p.item-wording 『#{@item.name}』は、#{@item.user.nickname}さんから出品されました。#{@item.category.name}の商品です。
    .item-table
      .item-image
        %figure-main
        =image_tag ("#{@item.images[0].name}")
      .item-profile
        %table{:border => "2"}
          %tr
            %th 出品者
            %td= link_to "#{@item.user.nickname}", "#"
          %tr
            %th カテゴリー
            %td #{@item.category.name}
          %tr
            %th 商品の状態
            %td #{@item.condition}
          %tr
            %th 配送料の負担
            %td #{@item.shipping_fee}
          %tr
            %th 配送の方法
            %td #{@item.shipping_method}
          %tr
            %th 配送元地域
            %td #{@item.shipping_from}
          %tr
            %th 発送日の目安
            %td #{@item.days_before_shipping}

    .item-price
      %span ¥#{@item.price.to_s(:delimited)}
      %span.tax-included (税込)
    - if current_user
      = render partial: 'items/buy-btn'
    .item-content
      %p.item-description  #{@item.description}

app/views/items/_other-item.html.haml
.item-detail__bottom
  .item-detail-box
    .item-list
      .item-list__name
        %h3 #{@item.user.nickname}のその他の出品
      .item-list__box
        .item-list__box-show
          - @whole_items.each do |item|
            .visibility
              = link_to item_path(item.id) do
                %figure
                  %figcaption.name
                    %span #{item.name}
                  .price
                    %span ¥#{item.price.to_s(:delimited)}
                    = image_tag ("#{item.images[0].name}")

app/views/items/edit.html.haml
- content_for :title do
  商品情報の編集
= render "shared/single-header"
.single-main
  .sell-container
    %h2.sell-container__title 商品の情報を入力
    .sell-contents
      = form_for @item, url: { action: "update" } do |f|
        = f.hidden_field :user_id, value: "#{current_user.id}"
        .sell-content
          .sell-content__images
            %h3 出品画像
            %span 必須
            %p 最大10枚までアップロードできます
            #sell-images-area
            .sell-content__image.item-edit-form
              = f.fields_for :images do |image|
                = image.file_field :name, class: "image_uploader"
        .sell-content
          = f.label :name, "商品名"
          %span 必須
          = f.text_field :name, placeholder: "商品名（必須40文字まで）", class: "input-default"
          .sell-content__margin
            = f.label :description, "商品の説明"
            %span 必須
            = f.text_area :description, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "textarea-default"
        .sell-content
          .sell-content__sub-head 
            %h3 商品の詳細
          .sell-content__groups
            .sell-content__group#sell-content-category
              = f.label :category_id, "カテゴリー"
              %span 必須
            .sell-selector#category0
              = f.collection_select :category_id, @category0, :id, :name, {include_blank: "---"}, class: "select-default"
              %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :condition, "商品の状態"
              %span 必須
              .sell-selector
                = f.select :condition, Item.conditions.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
        .sell-content
          .sell-content__sub-head 
            %h3 配送について
            %i.fa.fa-question-circle
          .sell-content__groups
            .sell-content__group
              = f.label :shipping_fee, "配送料の負担"
              %span 必須 
              .sell-selector  
                = f.select :shipping_fee, Item.shipping_fees.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :shipping_method, "発送の方法"
              %span 必須
              .sell-selector
                = f.select :shipping_method, Item.shipping_methods.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :shipping_from, "発送元の地域"
              %span 必須
              .sell-selector
                = f.collection_select :shipping_from, Prefecture.all, :id, :name, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :days_before_shipping, "発送までの日数"
              %span 必須
              .sell-selector
                = f.select :days_before_shipping, Item.days_before_shippings.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
        .sell-content
          .sell-content__sub-head
            %h3 販売価格(300〜9,999,999)
            %i.fa.fa-question-circle
          .sell-content__calc
            %ul
              %li.price
                .li-left.li-left-price
                  = f.label :price, "価格"
                  %span 必須
                .li-right
                  .li-right__input
                    %a &#165;
                    = f.text_field :price, placeholder: "例）300", class: "li-right__input-default"
              %li.commission
                .li-left 販売手数料(10%)
                .li-right#commission &#045;
              %li.profit
                .li-left 販売利益
                .li-right#profit &#045;
        .sell-content__submit
          - prohibited_items = link_to "禁止されている出品","#", target: :_blank
          - prohibited_conduct = link_to "行為","#", target: :_blank
          - counterfeit_goods = link_to "偽ブランドの販売", "#", target: :_blank
          - seller_terms = link_to "加盟店規約", "#"
          %P #{prohibited_items}、#{prohibited_conduct}を必ずご確認ください。
          %P またブランド品でシリアルナンバー等がある場合はご記載ください。#{counterfeit_goods}は犯罪であり処罰される可能性があります。
          %P また、出品をもちまして#{seller_terms}に同意したことになります。
          = f.submit '変更する', class: "submit-btn"
          = render partial: 'items/destroy-btn'
          = link_to 'もどる', :back, class:"back-btn"
= render "shared/single-footer"

app/views/items/index.html.haml
.wrapper
  = render partial: 'shared/header'
  = render partial: 'shared/slider'
  = render partial: 'shared/content'
  = render partial: 'shared/sell-btn'
  = render partial: 'shared/app-baner'
  = render partial: 'shared/footer'

app/views/items/new.html.haml
- content_for :title do
  商品の出品
= render "shared/single-header"
.single-main
  .sell-container
    %h2.sell-container__title 商品の情報を入力
    .sell-contents
      = form_for @item do |f|
        = f.hidden_field :user_id, value: "#{current_user.id}"
        .sell-content
          .sell-content__images
            %h3 出品画像
            %span 必須
            %p 最大10枚までアップロードできます
            #sell-images-area
            .sell-content__image.item-new-form
              = f.fields_for :images do |image|
                = image.file_field :name, class: "image_uploader"
        .sell-content
          = f.label :name, "商品名"
          %span 必須
          = f.text_field :name, placeholder: "商品名（必須40文字まで）", class: "input-default"
          .sell-content__margin
            = f.label :description, "商品の説明"
            %span 必須
            = f.text_area :description, placeholder: "商品の説明（必須1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "textarea-default"
        .sell-content
          .sell-content__sub-head 
            %h3 商品の詳細
          .sell-content__groups
            .sell-content__group#sell-content-category
              = f.label :category_id, "カテゴリー"
              %span 必須
            .sell-selector#category0
              = f.collection_select :category_id, @category0, :id, :name, {include_blank: "---"}, class: "select-default"
              %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :condition, "商品の状態"
              %span 必須
              .sell-selector
                = f.select :condition, Item.conditions.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
        .sell-content
          .sell-content__sub-head 
            %h3 配送について
            %i.fa.fa-question-circle
          .sell-content__groups
            .sell-content__group
              = f.label :shipping_fee, "配送料の負担"
              %span 必須 
              .sell-selector  
                = f.select :shipping_fee, Item.shipping_fees.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :shipping_method, "発送の方法"
              %span 必須
              .sell-selector
                = f.select :shipping_method, Item.shipping_methods.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :shipping_from, "発送元の地域"
              %span 必須
              .sell-selector
                = f.collection_select :shipping_from, Prefecture.all, :id, :name, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
            .sell-content__group.sell-content__margin
              = f.label :days_before_shipping, "発送までの日数"
              %span 必須
              .sell-selector
                = f.select :days_before_shipping, Item.days_before_shippings.keys, {include_blank: "---"}, class: "select-default"
                %i.fa.fa-chevron-down.select-default-arrow
        .sell-content
          .sell-content__sub-head
            %h3 販売価格(300〜9,999,999)
            %i.fa.fa-question-circle
          .sell-content__calc
            %ul
              %li.price
                .li-left.li-left-price
                  = f.label :price, "価格"
                  %span 必須
                .li-right
                  .li-right__input
                    %a &#165;
                    = f.text_field :price, placeholder: "例）300", class: "li-right__input-default"
              %li.commission
                .li-left 販売手数料(10%)
                .li-right#commission &#045;
              %li.profit
                .li-left 販売利益
                .li-right#profit &#045;
        .sell-content__submit
          - prohibited_items = link_to "禁止されている出品","#", target: :_blank
          - prohibited_conduct = link_to "行為","#", target: :_blank
          - counterfeit_goods = link_to "偽ブランドの販売", "#", target: :_blank
          - seller_terms = link_to "加盟店規約", "#"
          %P #{prohibited_items}、#{prohibited_conduct}を必ずご確認ください。
          %P またブランド品でシリアルナンバー等がある場合はご記載ください。#{counterfeit_goods}は犯罪であり処罰される可能性があります。
          %P また、出品をもちまして#{seller_terms}に同意したことになります。
          = f.submit '出品する', class: "submit-btn"
          = link_to 'もどる', :back, class:"back-btn"
= render "shared/single-footer"

app/views/items/search.html.haml
- content_for :title do
  #{@q.name_cont}の検索結果
.wrapper-search
  = render partial: "shared/header"
  //= render partial: "shared/breadcrumbs"

  .container
    .container__left
      .container__left__sort-area
        .container__left__sort-area__box
          並び変え

      .container__left__search-area
        .container__left__search-area__box

    .container__right
      .container__right__search-result
        .container__right__search-result__item-name
          = @q.name_cont
        .container__right__search-result__text
          の検索結果
      .container__right__displayed-results
        .container__right__displayed-results__display
          = "1-#{@items.length}件表示"
      .container__right__search-item
        .container__right__search-item__results
        - @items.each do |item|
          = link_to item_path(item) do
            .container__right__search-item__results__box
              .container__right__search-item__results__box__image-box
                = image_tag ("#{item.images[0].name}"), alt: '画像１', class: 'owl-box'
              .container__right__search-item__results__box__image-box__name-box
                = item.name
              .container__right__search-item__results__box__image-box__price
                = number_to_currency(item.price, format: "%u%n", unit: "¥", precision: 0 )

app/views/items/show.html.haml
- content_for :title do
  #{@item.name}
-# 以下は表示確認用なので削除してください。
.wrapper
  = render partial: 'shared/header'
  = render partial: 'items/item-detail'

  -# = render partial: 'items/item-comments'
  = render partial: 'items/other-item'
  = render partial: 'shared/app-baner'
  = render partial: 'shared/footer'