config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  # root to: 'home#index'
  devise_scope :user do
    get 'login',      to: 'users/sessions#new'
    post 'login',     to: 'users/sessions#create'
    get 'logout',     to: 'users/sessions#logout'
    delete 'logout',  to: 'users/sessions#destroy'
    get 'signup',     to: 'users/registrations#signup'
    get 'signup/registration',  to: 'users/registrations#new'
    # get 'signup/number',         to: 'users/registrations#number'
    # get 'signup/address',        to: 'users/registrations#address'
    get 'signup/credit',         to: 'users/registrations#credit'
    get 'signup/done',           to: 'users/registrations#done'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "items#index"

  resources :users, only: [:index, :show, :new] do
    collection do
      get 'identification', to: 'users#identification'
      get '/:id', to: 'users#show'
    end
    member do
      get 'profile/edit', to: 'profiles#edit'
    end
  end

  resources :signup ,only: [:index,:create] do
    collection do
      get 'sms_authentication' 
      post 'sms_authentication',to: 'signup#sms_post'
      get 'sms_confirmation' 
      post 'sms_confirmation',to: 'signup#sms_check'
      get 'address' 
    end
  end

  resources :items, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :images, only:[:index, :create]
    collection do
      get 'search', to: 'items#search'
    end
  end
    
  resources :card, only: [:new, :show] do
    collection do
      get "paying"
      post 'show',   to: 'card#show'
      post 'pay',    to: 'card#pay'
      post 'delete', to: 'card#delete'
    end
  end

  resources :purchase, only: [:index, :show] do
    collection do
      get  'show',  to: 'purchase#show'
      get  '/:id/index', to: 'purchase#index',as:"item_buy"
      post '/:id/pay',   to: 'purchase#pay',as:"item_pay"
      get  '/:id/done',  to: 'purchase#done',as:"buy_done"
    end
  end

  get 'guide/beginner', to: 'guide#beginner'

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :items
end

app/controllers/card_controller.rb
class CardController < ApplicationController
  
  require "payjp"

  def paying
    # 以下、パンくずリスト用の定義。ユーザーにカードの登録が結びついたときに使う。
    # @card = Card.find_by(id: params[:id])
    # @user = User.find_by(id: @card.user_id)
  end

  def new
    card = current_user.cards
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      p Payjp.api_key
      customer = Payjp::Customer.create(
      description: '登録テスト',
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = current_user.cards.first
    if card.present?
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
    redirect_to action: "paying"
  end

  def show
    card = current_user.cards.first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_SECRET_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/views/card/new.html.haml
- content_for :title do
  クレジットカード情報入力
.wrapper-wallets
  = render partial: 'shared/header'
  - breadcrumb :pay
  = render partial: 'render/breadcrumbs'
  .container
    .content-side-bar
    = render 'users/sidebar'
    .content
      .content__chapter1
        %h2.content__chapter1__head
          クレジットカード情報入力
        = form_with url: pay_card_index_path, method: :post, id: 'charge-form', class: 'card-form', html: { name: "inputForm" } do |f|
          .card-form__input
          .card-form__box
            .form-number
              %label.form-number__payment カード番号
              %span.form-number__require 必須
              = f.text_field :card_number, type: 'text', class: 'form-number__input', placeholder: '半角数字のみ', maxlength: "16", id: "card_number"
              %ul.form-number__error-text
              %ul.form-number__card-list
                %li.form-number__card-list__visa
                  = image_tag"visa.svg",class:"form-number__card-list__visa"
                %li.form-number__card-list__master
                  = image_tag"/images/master.svg",class:"form-number__card-list__master"
                %li.form-number__card-list__saison
                  = image_tag"/images/saison.svg",class:"form-number__card-list__saison"
                %li.form-number__card-list__jcb
                  = image_tag"/images/jcb.svg",class:"form-number__card-list__jcb"
                %li.form-number__card-list__american
                  = image_tag"/images/american.svg",class:"form-number__card-list__american"
                %li.form-number__card-list__dainers
                  = image_tag"/images/diners.svg",class:"form-number__card-list__dainers"
                %li.form-number__card-list__discover
                  = image_tag"/images/discover.svg",class:"form-number__card-list__discover"
            .form-signup
              = f.label :有効期限, class: 'form-signup__expire'
              %span.form-signup__require 必須
              %br
              .form-signup__month
                = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'form-signup__month__select', id: "exp_month"
                %i.form-signup__month__icon.fa.fa-chevron-down
              %span.form-signup__str 月
              %br
              .form-signup__year
                = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'form-signup__month__select', id: "exp_year"
                %i.form-signup__month__icon.fa.fa-chevron-down
              %span.form-signup__str 年
            .form-security
              = f.label :セキュリティコード, class: 'form-security__expire'
              %span.form-security__require 必須
              = f.text_field :cvc, type: 'text', class: 'form-security__input', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4", id: "cvc"
              %ul.form-security__error-message
              .form-security__info 
                %span.form-security__info__question ?
                カード裏面の番号とは？
            .btn-default#card_token
              = f.submit '追加する', class: 'form-btn', id: 'token_submit'
= render 'shared/sell-btn'
= render 'shared/app-baner'
= render 'shared/footer'

app/views/card/paying.html.haml
- content_for :title do
  支払い方法
.wrapper-wallets
  = render partial: 'shared/header'
  - breadcrumb :paying
  = render partial: 'render/breadcrumbs'
  .container
    .content-side-bar
    = render 'users/sidebar'
    .content
      .content__chapter2
        %h2.content__chapter2__head 
          支払い方法
        .card-index
          %section.card-index__title
            .card-index__title__head
              %h3.card-index__title__head__sub クレジットカード一覧
            %ul.card-index__title__list
          %section.card-index__add
            .card-index__add__card 
              = link_to new_card_path, method: :get, class: "card-index__add__card__text " do
                %i.card-index__add__card__icon.far.fa-credit-card
                  クレジットカードを追加
          .card-index__regist
            %a.card-index__regist__link
              %span.card-index__regist__link__text 支払い方法について
              %i.card-index__regist__link__icon.fas.fa-chevron-right
= render 'shared/sell-btn'
= render 'shared/app-baner'
= render 'shared/footer'

app/views/card/show.html.haml
- content_for :title do
  支払い方法
.wrapper-wallets
  = render partial: 'shared/header'
  - breadcrumb :pay
  = render partial: 'render/breadcrumbs'
  .container
    .content-side-bar
    = render 'users/sidebar'
    .content
      .content__chapter3
        %h2.content__chapter3__head 
          支払い方法
        .card-index
          %section.card-index__title
            .card-index__title__head
              %h3.card-index__title__head__sub クレジットカード一覧
            %ul.card-index__title__list
              %li.card-detail
                %div.card-detail__form
                  %figure
                    =image_tag"/images/visa.svg",class:"card-detail__form__image"
                  .card-detail__form__num
                    = "**** **** **** " + @default_card_information.last4
                  .card-detail__form__limit-num
                    - exp_month = @default_card_information.exp_month.to_s
                    - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
                    = exp_month + " / " + exp_year
                    = form_tag(delete_card_index_path, method: :post, id: 'charge-form',  name: "inputForm") do
                      %input{ type: "hidden", name: "card_id", value: "" }
                      %button.card-detail__form__remove 削除する
          .card-index__regist
            %a.card-index__regist__link
              %span.card-index__regist__link__text 支払い方法について
              %i.card-index__regist__link__icon.fa.fa-chevron-right
= render 'shared/sell-btn'
= render 'shared/app-baner'
= render 'shared/footer'